### PR TITLE
SVN 1.14.0

### PR DESCRIPTION
**Pull request by ahwm**
https://ci.appveyor.com/project/ahwm/svn-windows

### CODE REVIEW

**Comment by Jan-E** [comment]
Thanks! I will merge it after the Appveyor builds have completed. Let us hope the jobs will not be stopped by the 1 hour time limit on free Appveyor accounts.
BTW. I was already thinking of upgrading to this LTS release. First testing locally, then on Appveyor. The last one you have done now. And for the first one, I do know now how to do it.

**Comment by ahwm** [comment]
I ran them on my local system before as well with basically the same configuration. 🙂

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jan-E** [comment]
Your own Appveyor builds are a bit ahead of mine. It will be a close call for the 2nd job if it stays under the 60 minutes.

**Comment by ahwm** [comment]
It was almost finished with the test 119/121 when it stopped. I restarted the failed x64 build hoping it would be under the 60 minute limit.

Annoying thing is it doesn't take nearly that long on my local machine.

**Comment by Jan-E** [comment]
Sometimes you have to try a little later to rebuild the same jobs. My first rebuild with OpenSSL 1.1.1g timed out, the second succeeded.

**Comment by Jan-E** [comment]
https://ci.appveyor.com/project/Jan-E/svn-windows/history 

If the X64 builds allways time out we could add a third job without the tests.

**Comment by Jan-E** [comment]
Bad luck once again on your 2nd job

**Comment by Jan-E** [comment]
But it was closer. Stopped during 121/121.

**Comment by ahwm** [comment]
Here's my local build script 🙂

```bat
copy zlib-1.2.11\*.h .\Apache24\include
copy expat-2.2.9\lib\*.h .\Apache24\include /y

call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

cd \build-svn\zlib-1.2.11
nmake -f win32/Makefile.msc clean
nmake -f win32/Makefile.msc
copy *.lib \build-svn\Apache24\lib
copy *.dll \build-svn\Apache24\bin

set lib="C:\Program Files\OpenSSL-Win64\lib";\build-svn\zlib-1.2.11;\build-svn\Apache24\lib;%lib%
set include="C:\Program Files\OpenSSL-Win64\include";\build-svn\zlib-1.2.11;\build-svn\Apache24\include;%include%

cd \build-svn\subversion-1.14.0
C:\Python38\python gen-make.py --release -t vcproj --vsnet-version=2019 --with-apr-util=C:\build-svn\Apache24 --with-apr=C:\build-svn\Apache24 --with-apr-iconv=C:\build-svn\Apache24 --with-apr_memcache=C:\build-svn\Apache24 --with-httpd=C:\build-svn\Apache24 --with-openssl="C:\Program Files\OpenSSL-Win64" --with-zlib=C:\build-svn\Apache24 --with-sqlite=C:\build-svn\sqlite-amalgamation-3310100
devenv subversion_vcnet.sln /Build "Release|x64"

set path="C:\Program Files\OpenSSL-Win64\bin";C:\build-svn\Apache24\bin;C:\build-svn\subversion-1.14.0\Release;%path%

C:\Python38\python win-tests.py --release --cleanup

md \build-svn\svn\bin
md \build-svn\svn\lib
md \build-svn\svn\modules
cd \build-svn\subversion-1.14.0
for /r %%f in (*.dll, *.exe) do @copy "%%f" \build-svn\svn\bin /y
for /r %%f in (*.lib) do @copy "%%f" \build-svn\svn\lib /y
for /r %%f in (*.so) do @copy "%%f" \build-svn\svn\modules /y
cd \build-svn\svn
```

**Comment by ahwm** [comment]
Re-ran it locally and it ran in under 10 minutes complete with tests.

**Comment by Jan-E** [comment]
I asked @steffenal to include the Zlib libs and dll’s in his distribution. Skipping the Zlib builds might just be enough to stay under the 60 minutes.

**Comment by Jan-E** [comment]
Or we could try that ourselves. Put the Zlib builds somewhere on the net and let Appveyor fetch them.

**Comment by Jan-E** [comment]
I allways think that looking at the build log during the builds also takes CPU cycles on Appveyor. So I abstain from that.

**Comment by Jan-E** [comment]
Using a cachedversion of Zlib resulted in
https://ci.appveyor.com/project/Jan-E/svn-windows/builds/33190332
Completed in 59 min 42 sec. Just before the axe.

It should be possible to cache the build itself and run a separate job for the tests.

**Comment by Jan-E** [comment]
I reverted back to Python 2.7, because Python 3.8 reported a lot of errors that were no error at all. The subversion devs are busy preparing the build process for Python 3.8 on Windows, but apparently are not there yet.

Moreover, after long trial and error I managed to split the X64 build in 2 jobs.

**Pull request merged**
